
public class Main {
    public static void main(String[] args) {
        Game game = new Game();
        game.startGame();


    }
}
//TODO PRIOR FIX EXP SYSTEM: EXCEED EXP TRANSFER TO NEXT LVL
//TODO PRIOR Gold rewards
//TODO PRIOR Town MENU
//TODO PRIOR IF DUNGEON ARE CLEARED TRAVEL TO OTHER TOWN + REWARD;
//TODO PRIOR SAVE CHARACTER REWORK PUT GENERATORS INSIDE + CURRENT LOCATIONS
//TODO PRIOR EXP FOR A KILL REWORK

//TODO PASSIVE , ACTIVE SKILLS
//TODO WEARABLES ARMOR WEAPONS ETC + PRICES
//TODO INVENTORY MENU + WEIGHT
//TODO DROP SYSTEM WEARABLES (LOW CHANCE)
//TODO FIX COLORS IN ALL DIALOGS
//TODO TELEPORT BETWEEN CITIES
//TODO SHOW MESSAGE IF DUNGEON CLEARED
//TODO OPTIMIZE CODE BEFORE DEADLINE
