
public class Main {
    public static void main(String[] args) {
        Game game = new Game();
        game.startGame();


    }
}
//TODO Gold rewards
//TODO Town MENU
//TODO FIX EXP SYSTEM: EXCEED EXP TRANSFER TO NEXT LVL
//TODO FIRST NPC POTIONS ONLY?
//TODO PASSIVE , ACTIVE SKILLS
//TODO WEARABLES ARMOR WEAPONS ETC
//TODO INVENTORY MENU + WEIGHT
//TODO ITEM PRICES (DIV BY 2 FOR SELL PRICE)
//TODO DROP SYSTEM WEARABLES (LOW CHANCE)
//TODO EXP FOR A KILL REWORK