
public class Main {
    public static void main(String[] args) {
        Game game = new Game();
        game.startGame();


    }
}
//TODO Gold rewards
//TODO Town MENU
//TODO DUNGEON GENERATION + FILL UP MONSTERS ARRAY
//TODO FIX EXP SYSTEM: EXCEED EXP TRANSFER TO NEXT LVL
//TODO FIRST NPC POTIONS ONLY?
//TODO GENERATE ENEMY STATS BY LVL
//TODO PASSIVE , ACTIVE SKILLS
//TODO WEARABLES ARMOR WEAPONS ETC
//TODO INVENTORY MENU + WEIGHT